--decrypt
--wrapping-keys discovery=true discovery-account=REPLACE_WITH_YOUR_12_DIGIT_ACCOUNT_ID discovery-partition=aws
--commitment-policy require-encrypt-require-decrypt
--metadata-output output.json
--max-encrypted-data-keys 1
--buffer
--encryption-context purpose=backup
