--decrypt
--wrapping-keys key=${KMS_KEY_ARN}
--commitment-policy require-encrypt-require-decrypt
--metadata-output output.json
--max-encrypted-data-keys 1
--buffer
--encryption-context purpose=backup
